// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addChirp = `-- name: AddChirp :one
insert into chirps (id, created_at, updated_at, body, user_id)
values (gen_random_uuid(), now(), now(), $1, $2)
returning id, created_at, updated_at, body, user_id
`

type AddChirpParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) AddChirp(ctx context.Context, arg AddChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, addChirp, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const removeChirps = `-- name: RemoveChirps :exec
delete from chirps
`

func (q *Queries) RemoveChirps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeChirps)
	return err
}
