# Get metrics
GET http://localhost:8080/admin/metrics 
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
# Reset everything
POST http://localhost:8080/admin/reset 

###
# Add user to database
POST http://localhost:8080/api/users
content-type: application/json

{
  "email": "user@example.com",
  "password": "test"
}

###
# login with user
POST http://localhost:8080/api/login
content-type: application/json

{
  "email": "user@example.com",
  "password": "test"
}

###

POST http://localhost:8080/api/validate_chirp
content-type: application/json

{
    "body": "this is a short test"
}
###############################################
POST http://localhost:8080/api/validate_chirp
content-type: application/json

{
    "body": "this is a short test this is a short testthis is a short test this is a short test this is a short test this is a short test this is a short test this is a short test this is a short test"
}
###############################################
POST http://localhost:8080/api/validate_chirp
content-type: application/json

###############################################
POST http://localhost:8080/api/validate_chirp
content-type: application/json

{
    "body": "this is a short test kerfuffle"
}
###############################################

###

POST http://localhost:8080/api/chirps
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiJhYzllMTRkMi1mZTBhLTQ3MzUtOTg3MC1lODc4M2UzY2NiZTAiLCJleHAiOjE3NDIyOTUwNjIsImlhdCI6MTc0MjI5MTQ2Mn0.fGfwg7seEh0EXLm1AgeEGflFQHRmpeeltTGVskYoob8

{
    "body": "This fire",
    "user_id": "4b40e726-61b5-41c5-9aac-4067ae3d6577"
}

###

GET http://localhost:8080/api/chirps

###

GET http://localhost:8080/api/chirps/cd0c1d7b-aba5-42a1-9893-0b503cf2dbdc


###

GET http://localhost:8080/admin/tokens