# GET http://localhost:8080/admin/metrics 
# content-type: application/json

# {
#     "name": "sample",
#     "time": "Wed, 21 Oct 2015 18:27:50 GMT"
# }

# GET http://localhost:8080/admin/reset 


###############################################
# POST http://localhost:8080/api/validate_chirp
# content-type: application/json

# {
#     "body": "this is a short test"
# }
###############################################
# POST http://localhost:8080/api/validate_chirp
# content-type: application/json

# {
#     "body": "this is a short test this is a short testthis is a short test this is a short test this is a short test this is a short test this is a short test this is a short test this is a short test"
# }
# ###############################################
# POST http://localhost:8080/api/validate_chirp
# content-type: application/json

###############################################
POST http://localhost:8080/api/validate_chirp
content-type: application/json

{
    "body": "this is a short test kerfuffle"
}